# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main.ui'
##
## Created by: Qt User Interface Compiler version 6.4.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCommandLinkButton, QGroupBox, QHBoxLayout,
    QLabel, QListWidget, QListWidgetItem, QMainWindow,
    QMenuBar, QSizePolicy, QStatusBar, QTabWidget,
    QVBoxLayout, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1024, 768)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 1024, 721))
        font = QFont()
        font.setPointSize(14)
        self.tabWidget.setFont(font)
        self.tab_account = QWidget()
        self.tab_account.setObjectName(u"tab_account")
        self.groupBox_15 = QGroupBox(self.tab_account)
        self.groupBox_15.setObjectName(u"groupBox_15")
        self.groupBox_15.setGeometry(QRect(10, 20, 371, 661))
        font1 = QFont()
        font1.setPointSize(18)
        self.groupBox_15.setFont(font1)
        self.main_account_list = QListWidget(self.groupBox_15)
        self.main_account_list.setObjectName(u"main_account_list")
        self.main_account_list.setGeometry(QRect(10, 40, 351, 621))
        self.main_account_list.setFont(font)
        self.groupBox_16 = QGroupBox(self.tab_account)
        self.groupBox_16.setObjectName(u"groupBox_16")
        self.groupBox_16.setGeometry(QRect(390, 10, 611, 181))
        font2 = QFont()
        font2.setPointSize(15)
        self.groupBox_16.setFont(font2)
        self.layoutWidget = QWidget(self.groupBox_16)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(10, 30, 591, 141))
        self.verticalLayout_5 = QVBoxLayout(self.layoutWidget)
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5 = QHBoxLayout()
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.a_r_time = QLabel(self.layoutWidget)
        self.a_r_time.setObjectName(u"a_r_time")
        self.a_r_time.setFont(font1)

        self.horizontalLayout_5.addWidget(self.a_r_time)


        self.verticalLayout_5.addLayout(self.horizontalLayout_5)

        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.a_user = QLabel(self.layoutWidget)
        self.a_user.setObjectName(u"a_user")
        self.a_user.setFont(font1)

        self.horizontalLayout_2.addWidget(self.a_user)


        self.verticalLayout_5.addLayout(self.horizontalLayout_2)

        self.horizontalLayout_3 = QHBoxLayout()
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.a_pwd = QLabel(self.layoutWidget)
        self.a_pwd.setObjectName(u"a_pwd")
        self.a_pwd.setFont(font1)

        self.horizontalLayout_3.addWidget(self.a_pwd)


        self.verticalLayout_5.addLayout(self.horizontalLayout_3)

        self.horizontalLayout_4 = QHBoxLayout()
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.a_status = QLabel(self.layoutWidget)
        self.a_status.setObjectName(u"a_status")
        self.a_status.setFont(font1)

        self.horizontalLayout_4.addWidget(self.a_status)


        self.verticalLayout_5.addLayout(self.horizontalLayout_4)

        self.groupBox_17 = QGroupBox(self.tab_account)
        self.groupBox_17.setObjectName(u"groupBox_17")
        self.groupBox_17.setGeometry(QRect(390, 200, 611, 481))
        self.groupBox_17.setFont(font2)
        self.account_login_record = QListWidget(self.groupBox_17)
        self.account_login_record.setObjectName(u"account_login_record")
        self.account_login_record.setGeometry(QRect(10, 30, 591, 441))
        self.tabWidget.addTab(self.tab_account, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.groupBox = QGroupBox(self.tab_3)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(0, 40, 791, 331))
        font3 = QFont()
        font3.setPointSize(15)
        font3.setBold(False)
        self.groupBox.setFont(font3)
        self.realtime_monitor_i6_list = QListWidget(self.groupBox)
        self.realtime_monitor_i6_list.setObjectName(u"realtime_monitor_i6_list")
        self.realtime_monitor_i6_list.setGeometry(QRect(10, 30, 771, 291))
        self.realtime_monitor_i6_list.setFont(font)
        self.groupBox_2 = QGroupBox(self.tab_3)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(0, 370, 791, 321))
        self.groupBox_2.setFont(font3)
        self.realtime_monitor_i6_list_2 = QListWidget(self.groupBox_2)
        self.realtime_monitor_i6_list_2.setObjectName(u"realtime_monitor_i6_list_2")
        self.realtime_monitor_i6_list_2.setGeometry(QRect(10, 30, 771, 281))
        self.realtime_monitor_i6_list_2.setFont(font)
        self.layoutWidget1 = QWidget(self.tab_3)
        self.layoutWidget1.setObjectName(u"layoutWidget1")
        self.layoutWidget1.setGeometry(QRect(660, 10, 338, 38))
        self.horizontalLayout = QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.btn_start_monitor_i6 = QCommandLinkButton(self.layoutWidget1)
        self.btn_start_monitor_i6.setObjectName(u"btn_start_monitor_i6")
        self.btn_start_monitor_i6.setFont(font3)

        self.horizontalLayout.addWidget(self.btn_start_monitor_i6)

        self.btn_stop_monitor_i6 = QCommandLinkButton(self.layoutWidget1)
        self.btn_stop_monitor_i6.setObjectName(u"btn_stop_monitor_i6")
        self.btn_stop_monitor_i6.setFont(font3)

        self.horizontalLayout.addWidget(self.btn_stop_monitor_i6)

        self.groupBox_4 = QGroupBox(self.tab_3)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(800, 60, 201, 311))
        self.groupBox_4.setFont(font3)
        self.layoutWidget2 = QWidget(self.groupBox_4)
        self.layoutWidget2.setObjectName(u"layoutWidget2")
        self.layoutWidget2.setGeometry(QRect(10, 40, 181, 261))
        self.verticalLayout_2 = QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.monitor_now_time = QLabel(self.layoutWidget2)
        self.monitor_now_time.setObjectName(u"monitor_now_time")
        self.monitor_now_time.setFont(font)

        self.verticalLayout_2.addWidget(self.monitor_now_time)

        self.monitor_item1 = QLabel(self.layoutWidget2)
        self.monitor_item1.setObjectName(u"monitor_item1")
        self.monitor_item1.setFont(font)

        self.verticalLayout_2.addWidget(self.monitor_item1)

        self.monitor_item2 = QLabel(self.layoutWidget2)
        self.monitor_item2.setObjectName(u"monitor_item2")
        self.monitor_item2.setFont(font)

        self.verticalLayout_2.addWidget(self.monitor_item2)

        self.monitor_item3 = QLabel(self.layoutWidget2)
        self.monitor_item3.setObjectName(u"monitor_item3")
        self.monitor_item3.setFont(font)

        self.verticalLayout_2.addWidget(self.monitor_item3)

        self.groupBox_5 = QGroupBox(self.tab_3)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(800, 400, 201, 291))
        self.groupBox_5.setFont(font2)
        self.layoutWidget3 = QWidget(self.groupBox_5)
        self.layoutWidget3.setObjectName(u"layoutWidget3")
        self.layoutWidget3.setGeometry(QRect(10, 40, 181, 241))
        self.layoutWidget3.setFont(font2)
        self.verticalLayout_3 = QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.monitor_now_time_2 = QLabel(self.layoutWidget3)
        self.monitor_now_time_2.setObjectName(u"monitor_now_time_2")
        self.monitor_now_time_2.setFont(font)

        self.verticalLayout_3.addWidget(self.monitor_now_time_2)

        self.monitor_item1_2 = QLabel(self.layoutWidget3)
        self.monitor_item1_2.setObjectName(u"monitor_item1_2")
        self.monitor_item1_2.setFont(font)

        self.verticalLayout_3.addWidget(self.monitor_item1_2)

        self.monitor_item2_2 = QLabel(self.layoutWidget3)
        self.monitor_item2_2.setObjectName(u"monitor_item2_2")
        self.monitor_item2_2.setFont(font)

        self.verticalLayout_3.addWidget(self.monitor_item2_2)

        self.monitor_item3_2 = QLabel(self.layoutWidget3)
        self.monitor_item3_2.setObjectName(u"monitor_item3_2")
        self.monitor_item3_2.setFont(font)

        self.verticalLayout_3.addWidget(self.monitor_item3_2)

        self.monitor_item4_2 = QLabel(self.layoutWidget3)
        self.monitor_item4_2.setObjectName(u"monitor_item4_2")
        self.monitor_item4_2.setFont(font)

        self.verticalLayout_3.addWidget(self.monitor_item4_2)

        self.monitor_item5_2 = QLabel(self.layoutWidget3)
        self.monitor_item5_2.setObjectName(u"monitor_item5_2")
        self.monitor_item5_2.setFont(font)

        self.verticalLayout_3.addWidget(self.monitor_item5_2)

        self.tabWidget.addTab(self.tab_3, "")
        self.tab_backup = QWidget()
        self.tab_backup.setObjectName(u"tab_backup")
        self.groupBox_10 = QGroupBox(self.tab_backup)
        self.groupBox_10.setObjectName(u"groupBox_10")
        self.groupBox_10.setGeometry(QRect(510, 10, 241, 91))
        self.groupBox_10.setFont(font1)
        self.btn_reload_by_year = QCommandLinkButton(self.groupBox_10)
        self.btn_reload_by_year.setObjectName(u"btn_reload_by_year")
        self.btn_reload_by_year.setGeometry(QRect(10, 40, 221, 41))
        self.btn_reload_by_year.setFont(font3)
        self.groupBox_12 = QGroupBox(self.tab_backup)
        self.groupBox_12.setObjectName(u"groupBox_12")
        self.groupBox_12.setGeometry(QRect(10, 10, 481, 491))
        self.groupBox_12.setFont(font1)
        self.backup_by_year = QListWidget(self.groupBox_12)
        self.backup_by_year.setObjectName(u"backup_by_year")
        self.backup_by_year.setGeometry(QRect(10, 40, 461, 441))
        self.backup_by_year.setFont(font)
        self.tabWidget.addTab(self.tab_backup, "")
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.groupBox_8 = QGroupBox(self.tab)
        self.groupBox_8.setObjectName(u"groupBox_8")
        self.groupBox_8.setGeometry(QRect(510, 10, 251, 81))
        self.groupBox_8.setFont(font1)
        self.reload_final_record_by_month = QLabel(self.groupBox_8)
        self.reload_final_record_by_month.setObjectName(u"reload_final_record_by_month")
        self.reload_final_record_by_month.setGeometry(QRect(20, 40, 211, 31))
        self.reload_final_record_by_month.setFont(font)
        self.groupBox_9 = QGroupBox(self.tab)
        self.groupBox_9.setObjectName(u"groupBox_9")
        self.groupBox_9.setGeometry(QRect(510, 100, 251, 91))
        self.groupBox_9.setFont(font1)
        self.btn_reoad_by_month = QCommandLinkButton(self.groupBox_9)
        self.btn_reoad_by_month.setObjectName(u"btn_reoad_by_month")
        self.btn_reoad_by_month.setGeometry(QRect(10, 40, 231, 41))
        self.btn_reoad_by_month.setFont(font3)
        self.groupBox_11 = QGroupBox(self.tab)
        self.groupBox_11.setObjectName(u"groupBox_11")
        self.groupBox_11.setGeometry(QRect(10, 10, 481, 501))
        self.groupBox_11.setFont(font1)
        self.backup_by_month = QListWidget(self.groupBox_11)
        self.backup_by_month.setObjectName(u"backup_by_month")
        self.backup_by_month.setGeometry(QRect(10, 40, 461, 451))
        self.backup_by_month.setFont(font)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.groupBox_6 = QGroupBox(self.tab_2)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setGeometry(QRect(510, 120, 251, 211))
        self.groupBox_6.setFont(font1)
        self.layoutWidget4 = QWidget(self.groupBox_6)
        self.layoutWidget4.setObjectName(u"layoutWidget4")
        self.layoutWidget4.setGeometry(QRect(10, 40, 231, 161))
        self.verticalLayout_8 = QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_8.setObjectName(u"verticalLayout_8")
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.btn_reload_by_day = QCommandLinkButton(self.layoutWidget4)
        self.btn_reload_by_day.setObjectName(u"btn_reload_by_day")
        self.btn_reload_by_day.setFont(font3)

        self.verticalLayout_8.addWidget(self.btn_reload_by_day)

        self.btn_start_auto_reload_by_day = QCommandLinkButton(self.layoutWidget4)
        self.btn_start_auto_reload_by_day.setObjectName(u"btn_start_auto_reload_by_day")
        self.btn_start_auto_reload_by_day.setFont(font3)
        self.btn_start_auto_reload_by_day.setInputMethodHints(Qt.ImhPreferLatin|Qt.ImhPreferUppercase)

        self.verticalLayout_8.addWidget(self.btn_start_auto_reload_by_day)

        self.btn_stop_auto_reload_by_day = QCommandLinkButton(self.layoutWidget4)
        self.btn_stop_auto_reload_by_day.setObjectName(u"btn_stop_auto_reload_by_day")
        self.btn_stop_auto_reload_by_day.setFont(font3)

        self.verticalLayout_8.addWidget(self.btn_stop_auto_reload_by_day)

        self.groupBox_7 = QGroupBox(self.tab_2)
        self.groupBox_7.setObjectName(u"groupBox_7")
        self.groupBox_7.setGeometry(QRect(510, 10, 251, 81))
        self.groupBox_7.setFont(font1)
        self.reload_final_record_by_day = QLabel(self.groupBox_7)
        self.reload_final_record_by_day.setObjectName(u"reload_final_record_by_day")
        self.reload_final_record_by_day.setGeometry(QRect(20, 38, 201, 31))
        self.reload_final_record_by_day.setFont(font2)
        self.groupBox_13 = QGroupBox(self.tab_2)
        self.groupBox_13.setObjectName(u"groupBox_13")
        self.groupBox_13.setGeometry(QRect(10, 10, 481, 491))
        self.groupBox_13.setFont(font1)
        self.backup_by_day = QListWidget(self.groupBox_13)
        self.backup_by_day.setObjectName(u"backup_by_day")
        self.backup_by_day.setGeometry(QRect(10, 40, 461, 441))
        self.backup_by_day.setFont(font)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.layoutWidget5 = QWidget(self.tab_4)
        self.layoutWidget5.setObjectName(u"layoutWidget5")
        self.layoutWidget5.setGeometry(QRect(430, 170, 381, 54))
        self.verticalLayout_7 = QVBoxLayout(self.layoutWidget5)
        self.verticalLayout_7.setObjectName(u"verticalLayout_7")
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.downloa_first_record = QLabel(self.layoutWidget5)
        self.downloa_first_record.setObjectName(u"downloa_first_record")
        self.downloa_first_record.setFont(font)

        self.verticalLayout_7.addWidget(self.downloa_first_record)

        self.download_last_record = QLabel(self.layoutWidget5)
        self.download_last_record.setObjectName(u"download_last_record")
        self.download_last_record.setFont(font)

        self.verticalLayout_7.addWidget(self.download_last_record)

        self.groupBox_3 = QGroupBox(self.tab_4)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(420, 10, 401, 121))
        self.groupBox_3.setFont(font1)
        self.layoutWidget6 = QWidget(self.groupBox_3)
        self.layoutWidget6.setObjectName(u"layoutWidget6")
        self.layoutWidget6.setGeometry(QRect(10, 50, 381, 54))
        self.verticalLayout_6 = QVBoxLayout(self.layoutWidget6)
        self.verticalLayout_6.setObjectName(u"verticalLayout_6")
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.label = QLabel(self.layoutWidget6)
        self.label.setObjectName(u"label")
        self.label.setFont(font)

        self.verticalLayout_6.addWidget(self.label)

        self.label_2 = QLabel(self.layoutWidget6)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setFont(font)

        self.verticalLayout_6.addWidget(self.label_2)

        self.groupBox_14 = QGroupBox(self.tab_4)
        self.groupBox_14.setObjectName(u"groupBox_14")
        self.groupBox_14.setGeometry(QRect(10, 10, 401, 501))
        self.groupBox_14.setFont(font1)
        self.download_list = QListWidget(self.groupBox_14)
        self.download_list.setObjectName(u"download_list")
        self.download_list.setGeometry(QRect(10, 40, 381, 451))
        self.download_list.setFont(font)
        self.tabWidget.addTab(self.tab_4, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1024, 24))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.groupBox_15.setTitle(QCoreApplication.translate("MainWindow", u"Account list", None))
        self.groupBox_16.setTitle(QCoreApplication.translate("MainWindow", u"status", None))
        self.a_r_time.setText("")
        self.a_user.setText("")
        self.a_pwd.setText("")
        self.a_status.setText("")
        self.groupBox_17.setTitle(QCoreApplication.translate("MainWindow", u"login record", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_account), QCoreApplication.translate("MainWindow", u"Account", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"I6-1", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"I6-2", None))
        self.btn_start_monitor_i6.setText(QCoreApplication.translate("MainWindow", u"start monitor", None))
        self.btn_stop_monitor_i6.setText(QCoreApplication.translate("MainWindow", u"stop monitor", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("MainWindow", u"I6-1 realtime update", None))
        self.monitor_now_time.setText("")
        self.monitor_item1.setText("")
        self.monitor_item2.setText("")
        self.monitor_item3.setText("")
        self.groupBox_5.setTitle(QCoreApplication.translate("MainWindow", u"I6-2 realtime update", None))
        self.monitor_now_time_2.setText("")
        self.monitor_item1_2.setText("")
        self.monitor_item2_2.setText("")
        self.monitor_item3_2.setText("")
        self.monitor_item4_2.setText("")
        self.monitor_item5_2.setText("")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("MainWindow", u"Realtime monitor", None))
        self.groupBox_10.setTitle(QCoreApplication.translate("MainWindow", u"function", None))
        self.btn_reload_by_year.setText(QCoreApplication.translate("MainWindow", u"Reload", None))
        self.groupBox_12.setTitle(QCoreApplication.translate("MainWindow", u"by year", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_backup), QCoreApplication.translate("MainWindow", u"Backup by year", None))
        self.groupBox_8.setTitle(QCoreApplication.translate("MainWindow", u"update", None))
        self.reload_final_record_by_month.setText("")
        self.groupBox_9.setTitle(QCoreApplication.translate("MainWindow", u"function", None))
        self.btn_reoad_by_month.setText(QCoreApplication.translate("MainWindow", u"Reload", None))
        self.groupBox_11.setTitle(QCoreApplication.translate("MainWindow", u"by month", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"Backup by month", None))
        self.groupBox_6.setTitle(QCoreApplication.translate("MainWindow", u"function", None))
        self.btn_reload_by_day.setText(QCoreApplication.translate("MainWindow", u"Reload", None))
#if QT_CONFIG(statustip)
        self.btn_start_auto_reload_by_day.setStatusTip("")
#endif // QT_CONFIG(statustip)
        self.btn_start_auto_reload_by_day.setText(QCoreApplication.translate("MainWindow", u"Start auto reload", None))
        self.btn_stop_auto_reload_by_day.setText(QCoreApplication.translate("MainWindow", u"Stop auto reload", None))
        self.groupBox_7.setTitle(QCoreApplication.translate("MainWindow", u"update", None))
        self.reload_final_record_by_day.setText("")
        self.groupBox_13.setTitle(QCoreApplication.translate("MainWindow", u"by day", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"Backup by day", None))
        self.downloa_first_record.setText("")
        self.download_last_record.setText("")
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"Memo", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"clicked : show detail data by day", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"double clicked : download PDF file by day", None))
        self.groupBox_14.setTitle(QCoreApplication.translate("MainWindow", u"download PDF file by day", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QCoreApplication.translate("MainWindow", u"Download file", None))
    # retranslateUi

